Include reference to added reference to the The EPUB Accessibility exemption property
w3c/a11y-discov-vocab pull request #115
Opened 2024-07-30 14:33 UTC by clapierre

2024-07-30 14:42 UTC, mattgarrish commented
I'd also link the three references to the property in the table -- the ones with the text "a11y:exemption with the text string ...".

2024-07-30 17:51 UTC, mattgarrish commented
I was kind of surprised to find that the values didn't have linkable ids. It's not a big table of values, but still.

Maybe we should update that note first to add them, since republishing notes doesn't require any special process.

2024-07-30 19:14 UTC, clapierre commented
I noticed that too.  If you add the Id's to the Note I will update all of these references.

2024-09-05 17:33 UTC, mattgarrish requested changes

2024-09-05 17:33 UTC, mattgarrish commented on crosswalk/index.html
> +					<tr id="eaa-microenterprise">
We don't need IDs here, although maybe they don't hurt anything. It was the note that we needed to deep link into and that's done now. For this document, it's the hyperlinks that need to be fixed to be more specific. I'll suggest the changes for each. I'll create suggestions to remove the IDs but feel free to ignore the suggestions if you want to keep them.

2024-09-05 17:33 UTC, mattgarrish commented on crosswalk/index.html
> +							<p><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#exemption-property">a11y:exemption</a></code> with the text string<br/><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#ex
```suggestion
							<p><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#exemption-property">a11y:exemption</a></code> with the text string<br/><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#eaa-microenterprise">eaa-microenterprise</a></code></p>
```

2024-09-05 17:33 UTC, mattgarrish commented on crosswalk/index.html
> +							<p><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#exemption-property">a11y:exemption</a></code> with the text string<br/><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#ex
```suggestion
							<p><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#exemption-property">a11y:exemption</a></code> with the text string<br/><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#eaa-disproportionate-burden">eaa-disproportionate-burden</a></code></p>
```

2024-09-05 17:33 UTC, mattgarrish commented on crosswalk/index.html
> +							<p><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#exemption-property">a11y:exemption</a></code> with the text string<br/><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#ex
```suggestion
							<p><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#exemption-property">a11y:exemption</a></code> with the text string<br/><code><a href="https://www.w3.org/TR/epub-a11y-exemption/#eaa-fundamental-alteration">eaa-fundamental-alteration</a></code></p>
```

2024-09-05 17:33 UTC, mattgarrish commented on crosswalk/index.html
> +					<tr id="eaa-fundamental-alteration">
```suggestion
					<tr>
```

2024-09-05 17:33 UTC, mattgarrish commented on crosswalk/index.html
> +					<tr id="eaa-disproportionate-burden">
```suggestion
					<tr>
```

2024-09-05 17:33 UTC, mattgarrish commented on crosswalk/index.html
> +					<tr id="eaa-microenterprise">
```suggestion
					<tr>
```

2024-09-05 18:50 UTC, clapierre commented
Thanks @mattgarrish, all should now be addressed.

2024-09-05 19:18 UTC, merged