updated how to handle conformsTo
w3c/a11y-discov-vocab pull request #96
Opened 2023-10-12 18:28 UTC by clapierre

Decided to remove the old 1.0 IDPF URLs since we probably don't want to promote that even for EPUB 3.2 as this new method with text strings is backward compatible.

Also added all WCAG 2.0, 2.1, and 2.2 A/AA/AA variations as each have their own ONIX set of codes.

2023-10-12 18:46 UTC, mattgarrish requested changes
I'm fine with adding the new identifiers, but the change to the 1.0 URLs has to be reverted as I've noted.

2023-10-12 18:46 UTC, mattgarrish commented on crosswalk/index.html
> +                                <code>EPUB Accessibility 1.0 - WCAG 2.0 Level A</code></p>
These 1.0 text strings aren't valid per the 1.0 or 1.1 specifications, so if people were to use these they wouldn't conform to either. They have to map to the old IDPF URLs for 1.0 conformance.

2023-10-12 18:46 UTC, mattgarrish commented on crosswalk/index.html
> +                                <code>EPUB Accessibility 1.0 - WCAG 2.0 Level AA</code></p>
Same as previous comment.

2023-10-12 18:55 UTC, clapierre commented
reverted to 1.0 URLs for conformsTo.

2023-10-12 19:04 UTC, mattgarrish commented
What you might do instead @clapierre is move the 1.0 conformance _after_ the 1.1 so that people reach the new conformance statements first.

2023-10-13 04:20 UTC, gregoriopellegrino commented
Hi, are these changes a result of the draft crosswalk proposed by EditEUR?

2023-10-13 13:08 UTC, clapierre commented
@gregoriopellegrino  Actually these changes are a result of the new EPUB 1.1 Accessibility changes to conformsTo along with the new additions to ONIX as outlined in #95

2023-10-13 13:23 UTC, mattgarrish commented
Looks good to me now.

If you want a preview of the document: https://raw.githack.com/w3c/a11y-discov-vocab/19fa59f444ce5eaf8bf3d96219b6239e0c908fb9/crosswalk/index.html

2023-10-14 08:38 UTC, gregoriopellegrino commented
Fine for me, then I suggest to work on the complete mapping

2023-10-16 14:59 UTC, merged

2023-10-16 14:59 UTC, clapierre commented
Agreed Gregorio will work on the rest, wanted this merged first.

2023-10-16 15:21 UTC, mattgarrish commented
Should we republish the crosswalk now or wait until the rest of the mappings are updated?

2023-10-16 17:05 UTC, clapierre commented
Lets wait until I have the remaining items I was thinking of.
@gregoriopellegrino  do you agree with these?

accessibilityFeature:
ARIA (196:30)
displayTransformability (196:36)
highContrastDisplay (196:37)
latex (196:35)
unknown (196:08)
Did I miss any?

We need to also remove section accessibilityAPI (as we have removed this)

We also need to address the EAA exceptions:
75 EAA exception 1 – Micro-enterprises
76 EAA exception 2 – Disproportionate burden
77 EAA exception 3 – Fundamental modification

What were we thinking on how to handle this @mattgarrish?

2023-10-26 14:47 UTC, madeleinerothberg commented
I see one more to add:

Onix 196:52 All non-decorative content supports reading without sight 

Match for accessModeSufficient=textual and also accessMode=textual, both part of the calculation for what was called "Screen reader friendly" which is now "Supports nonvisual reading". This replaces the current cumbersome crosswalk to multiple codes in ONIX.

2023-10-26 16:44 UTC, chrisONIX commented
Here are some suggested proposals for crosswalk to ONIX - based on missing ONIX values in current version
 - latest version of code lists for ONIX are available here. [https://ns.editeur.org/onix/en]
 **Accessibility features**
audioDescription - List 196 - code 28
braille - List 21 - code BRL (Braille edition) - there are other options as well. List 175 - code BRF - format is digital braille
describedMath - List 196 - code 14 (Should be used with List 81 - code 48 - Mathematical content)
displayTransformability - List 196 - code 36
highContrastAudio - List 196 - code 27
highContrastDisplay - List 196 - codes 26 & 37
largePrint - code list 21 - codes LTE and ULP 
latex - code list 196 - code 35 (Should be used with List 81 - code 48 - Mathematical content)
none - code list 196 - code 09
page navigation - code list 196 - code 19
structuralNavigation - code list 196 - code 29
taggedPDF - code list 196 - code 05
unknown - code list 196 - code 08
unlocked - code list 144 - code 00

**Hazards**
flashing - code list 143 - code 13
noFlashingHazard -code list 143 - code 14
motionSimulation - code list 143 - code 17
noMotionSimulationHazard - code list 143 - code 18
sound - code list 143 - code 15
noSoundHazard - code list 143 - code 16
unknown - code list 196 - code 08

**Access Mode**
Access mode is dealt with in list 81 - which covers all digital products and their features for all the market.
We encourage users to also use values from 196 - confirming accessibility. 

auditory - code list 81 - main code 01 (plus 22, 13, 03, 04, 21, 22, 23) - covers the variety of audio content
chemOnVisual - code list 81 - code 47
colorDependent (ONIX does the other way around - see code list 196 _ code 25
mathOnVisual -code list 81 - code 48
musicOnVisual - code list 81 - code 11
textOnVisual - code list 81 - code 49
textual - code list 81 - main code 10 (plus codes 16, 45)
visual - code list 81 - codes 07, 18, 19, 20, 12, 46, 42, 50, 24

**Access Mode Sufficient**

textual - code list 196 - code 52.

2023-10-26 16:46 UTC, chrisONIX commented
We also have reserved some codes for future updates but we are waiting for feedback.
captions - waiting for confirmation if we need Open and closed captions or just single code?
ruby _ waiting feedback from Japanese ONIX users
signLanguage_ reserved code _waiting confirmation of use

tactileGraphic, tactical Object, - reserved code  - waiting for confirmation of use 
timingControl - reserved code  - waiting for confirmation of use
Transcript  - reserved code - waiting for confirmation of use

also accessModeSufficient  - auditory, visual and tactile